version: '3.1'
# services:
#   postgres:
#     profiles: [ "all", "postgres", "database" ]
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: schoolmag
    

services:
  cabin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: root
      MYSQL_USER: password
      MYSQL_PASSWORD: password
